# Generated by Django 5.0.1 on 2024-01-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inputs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of input (could be player, book, or specific instrument.",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Outputs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of output (e.g. keys monitor, SL monitor, main, etc.)",
                        max_length=100,
                    ),
                ),
                ("inputs", models.ManyToManyField(to="ios.inputs")),
            ],
        ),
    ]
