# Generated by Django 5.0.1 on 2024-01-27 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ios", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Inputs",
            new_name="Input",
        ),
        migrations.RenameModel(
            old_name="Outputs",
            new_name="Output",
        ),
    ]
