# Generated by Django 5.0.1 on 2024-01-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ios", "0005_alter_request_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
